version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: sitel-redis
    ports: 
      - "6379:6379"
      - "8001:8001"
    networks:
      - sitel-net

  mongo:
    image: mongo:latest
    container_name: sitel-mongo
    ports:
      - "27017:27017"
    networks:
      - sitel-net

  sitel-iam:
    build:
      context: ./sitel-iam
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_HOST=sitel-mongo
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=INFO
      - SITEL_SESSION_HOST=sitel-session
    ports:
      - "3002:3002"
    networks:
      - sitel-net
    container_name: sitel-iam
    depends_on:
      - mongo
    
  sitel-session:
    build:
      context: ./sitel-session
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=sitel-redis
      - REDIS_PORT=6379
    ports:
      - "3003:3003"
    networks:
      - sitel-net
    container_name: sitel-session
    depends_on:
      - redis

networks:
  sitel-net:
    driver: bridge